#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_PR_01_Clinicas.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbClinica")]
	public partial class DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InserttbCategoria(tbCategoria instance);
    partial void UpdatetbCategoria(tbCategoria instance);
    partial void DeletetbCategoria(tbCategoria instance);
    partial void InserttbUsuario(tbUsuario instance);
    partial void UpdatetbUsuario(tbUsuario instance);
    partial void DeletetbUsuario(tbUsuario instance);
    partial void InserttbDetalleEntrada(tbDetalleEntrada instance);
    partial void UpdatetbDetalleEntrada(tbDetalleEntrada instance);
    partial void DeletetbDetalleEntrada(tbDetalleEntrada instance);
    partial void InserttbDetalleSalida(tbDetalleSalida instance);
    partial void UpdatetbDetalleSalida(tbDetalleSalida instance);
    partial void DeletetbDetalleSalida(tbDetalleSalida instance);
    partial void InserttbEntrada(tbEntrada instance);
    partial void UpdatetbEntrada(tbEntrada instance);
    partial void DeletetbEntrada(tbEntrada instance);
    partial void InserttbPersona(tbPersona instance);
    partial void UpdatetbPersona(tbPersona instance);
    partial void DeletetbPersona(tbPersona instance);
    partial void InserttbPresentacion(tbPresentacion instance);
    partial void UpdatetbPresentacion(tbPresentacion instance);
    partial void DeletetbPresentacion(tbPresentacion instance);
    partial void InserttbProducto(tbProducto instance);
    partial void UpdatetbProducto(tbProducto instance);
    partial void DeletetbProducto(tbProducto instance);
    partial void InserttbSalida(tbSalida instance);
    partial void UpdatetbSalida(tbSalida instance);
    partial void DeletetbSalida(tbSalida instance);
    partial void InserttbTipoPersona(tbTipoPersona instance);
    partial void UpdatetbTipoPersona(tbTipoPersona instance);
    partial void DeletetbTipoPersona(tbTipoPersona instance);
    partial void InserttbTipoSalida(tbTipoSalida instance);
    partial void UpdatetbTipoSalida(tbTipoSalida instance);
    partial void DeletetbTipoSalida(tbTipoSalida instance);
    partial void InserttbTipoVenta(tbTipoVenta instance);
    partial void UpdatetbTipoVenta(tbTipoVenta instance);
    partial void DeletetbTipoVenta(tbTipoVenta instance);
    #endregion
		
		public DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dbClinicaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbCategoria> tbCategoria
		{
			get
			{
				return this.GetTable<tbCategoria>();
			}
		}
		
		public System.Data.Linq.Table<tbUsuario> tbUsuario
		{
			get
			{
				return this.GetTable<tbUsuario>();
			}
		}
		
		public System.Data.Linq.Table<tbDetalleEntrada> tbDetalleEntrada
		{
			get
			{
				return this.GetTable<tbDetalleEntrada>();
			}
		}
		
		public System.Data.Linq.Table<tbDetalleSalida> tbDetalleSalida
		{
			get
			{
				return this.GetTable<tbDetalleSalida>();
			}
		}
		
		public System.Data.Linq.Table<tbEntrada> tbEntrada
		{
			get
			{
				return this.GetTable<tbEntrada>();
			}
		}
		
		public System.Data.Linq.Table<tbPersona> tbPersona
		{
			get
			{
				return this.GetTable<tbPersona>();
			}
		}
		
		public System.Data.Linq.Table<tbPresentacion> tbPresentacion
		{
			get
			{
				return this.GetTable<tbPresentacion>();
			}
		}
		
		public System.Data.Linq.Table<tbProducto> tbProducto
		{
			get
			{
				return this.GetTable<tbProducto>();
			}
		}
		
		public System.Data.Linq.Table<tbSalida> tbSalida
		{
			get
			{
				return this.GetTable<tbSalida>();
			}
		}
		
		public System.Data.Linq.Table<tbTipoPersona> tbTipoPersona
		{
			get
			{
				return this.GetTable<tbTipoPersona>();
			}
		}
		
		public System.Data.Linq.Table<tbTipoSalida> tbTipoSalida
		{
			get
			{
				return this.GetTable<tbTipoSalida>();
			}
		}
		
		public System.Data.Linq.Table<tbTipoVenta> tbTipoVenta
		{
			get
			{
				return this.GetTable<tbTipoVenta>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbCategoria")]
	public partial class tbCategoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codCategoria;
		
		private string _categoria;
		
		private EntitySet<tbProducto> _tbProducto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodCategoriaChanging(int value);
    partial void OncodCategoriaChanged();
    partial void OncategoriaChanging(string value);
    partial void OncategoriaChanged();
    #endregion
		
		public tbCategoria()
		{
			this._tbProducto = new EntitySet<tbProducto>(new Action<tbProducto>(this.attach_tbProducto), new Action<tbProducto>(this.detach_tbProducto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCategoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codCategoria
		{
			get
			{
				return this._codCategoria;
			}
			set
			{
				if ((this._codCategoria != value))
				{
					this.OncodCategoriaChanging(value);
					this.SendPropertyChanging();
					this._codCategoria = value;
					this.SendPropertyChanged("codCategoria");
					this.OncodCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categoria", DbType="VarChar(50)")]
		public string categoria
		{
			get
			{
				return this._categoria;
			}
			set
			{
				if ((this._categoria != value))
				{
					this.OncategoriaChanging(value);
					this.SendPropertyChanging();
					this._categoria = value;
					this.SendPropertyChanged("categoria");
					this.OncategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbCategoria_tbProducto", Storage="_tbProducto", ThisKey="codCategoria", OtherKey="codProducto")]
		public EntitySet<tbProducto> tbProducto
		{
			get
			{
				return this._tbProducto;
			}
			set
			{
				this._tbProducto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbProducto(tbProducto entity)
		{
			this.SendPropertyChanging();
			entity.tbCategoria = this;
		}
		
		private void detach_tbProducto(tbProducto entity)
		{
			this.SendPropertyChanging();
			entity.tbCategoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbUsuario")]
	public partial class tbUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codPersona;
		
		private string _usuario;
		
		private string _contraseña;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodPersonaChanging(int value);
    partial void OncodPersonaChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    #endregion
		
		public tbUsuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPersona", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int codPersona
		{
			get
			{
				return this._codPersona;
			}
			set
			{
				if ((this._codPersona != value))
				{
					this.OncodPersonaChanging(value);
					this.SendPropertyChanging();
					this._codPersona = value;
					this.SendPropertyChanged("codPersona");
					this.OncodPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(50)")]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="VarChar(50)")]
		public string contraseña
		{
			get
			{
				return this._contraseña;
			}
			set
			{
				if ((this._contraseña != value))
				{
					this.OncontraseñaChanging(value);
					this.SendPropertyChanging();
					this._contraseña = value;
					this.SendPropertyChanged("contraseña");
					this.OncontraseñaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbDetalleEntrada")]
	public partial class tbDetalleEntrada : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codEntrada;
		
		private int _codProducto;
		
		private System.Nullable<int> _cantidad;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodEntradaChanging(int value);
    partial void OncodEntradaChanged();
    partial void OncodProductoChanging(int value);
    partial void OncodProductoChanged();
    partial void OncantidadChanging(System.Nullable<int> value);
    partial void OncantidadChanged();
    #endregion
		
		public tbDetalleEntrada()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEntrada", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int codEntrada
		{
			get
			{
				return this._codEntrada;
			}
			set
			{
				if ((this._codEntrada != value))
				{
					this.OncodEntradaChanging(value);
					this.SendPropertyChanging();
					this._codEntrada = value;
					this.SendPropertyChanged("codEntrada");
					this.OncodEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					this.OncodProductoChanging(value);
					this.SendPropertyChanging();
					this._codProducto = value;
					this.SendPropertyChanged("codProducto");
					this.OncodProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbDetalleSalida")]
	public partial class tbDetalleSalida : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codSalida;
		
		private int _codProducto;
		
		private System.Nullable<int> _cantidad;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodSalidaChanging(int value);
    partial void OncodSalidaChanged();
    partial void OncodProductoChanging(int value);
    partial void OncodProductoChanged();
    partial void OncantidadChanging(System.Nullable<int> value);
    partial void OncantidadChanged();
    #endregion
		
		public tbDetalleSalida()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codSalida", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int codSalida
		{
			get
			{
				return this._codSalida;
			}
			set
			{
				if ((this._codSalida != value))
				{
					this.OncodSalidaChanging(value);
					this.SendPropertyChanging();
					this._codSalida = value;
					this.SendPropertyChanged("codSalida");
					this.OncodSalidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					this.OncodProductoChanging(value);
					this.SendPropertyChanging();
					this._codProducto = value;
					this.SendPropertyChanged("codProducto");
					this.OncodProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int")]
		public System.Nullable<int> cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbEntrada")]
	public partial class tbEntrada : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codEntrada;
		
		private System.Nullable<System.DateTime> _fechaEntrada;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodEntradaChanging(int value);
    partial void OncodEntradaChanged();
    partial void OnfechaEntradaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaEntradaChanged();
    #endregion
		
		public tbEntrada()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codEntrada", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codEntrada
		{
			get
			{
				return this._codEntrada;
			}
			set
			{
				if ((this._codEntrada != value))
				{
					this.OncodEntradaChanging(value);
					this.SendPropertyChanging();
					this._codEntrada = value;
					this.SendPropertyChanged("codEntrada");
					this.OncodEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaEntrada", DbType="Date")]
		public System.Nullable<System.DateTime> fechaEntrada
		{
			get
			{
				return this._fechaEntrada;
			}
			set
			{
				if ((this._fechaEntrada != value))
				{
					this.OnfechaEntradaChanging(value);
					this.SendPropertyChanging();
					this._fechaEntrada = value;
					this.SendPropertyChanged("fechaEntrada");
					this.OnfechaEntradaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbPersona")]
	public partial class tbPersona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codPersona;
		
		private System.Nullable<int> _codTipoPersona;
		
		private string _nombre;
		
		private string _dpi;
		
		private System.Nullable<System.DateTime> _fechaNacimiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodPersonaChanging(int value);
    partial void OncodPersonaChanged();
    partial void OncodTipoPersonaChanging(System.Nullable<int> value);
    partial void OncodTipoPersonaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndpiChanging(string value);
    partial void OndpiChanged();
    partial void OnfechaNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaNacimientoChanged();
    #endregion
		
		public tbPersona()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPersona", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codPersona
		{
			get
			{
				return this._codPersona;
			}
			set
			{
				if ((this._codPersona != value))
				{
					this.OncodPersonaChanging(value);
					this.SendPropertyChanging();
					this._codPersona = value;
					this.SendPropertyChanged("codPersona");
					this.OncodPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codTipoPersona", DbType="Int")]
		public System.Nullable<int> codTipoPersona
		{
			get
			{
				return this._codTipoPersona;
			}
			set
			{
				if ((this._codTipoPersona != value))
				{
					this.OncodTipoPersonaChanging(value);
					this.SendPropertyChanging();
					this._codTipoPersona = value;
					this.SendPropertyChanged("codTipoPersona");
					this.OncodTipoPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(100)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dpi", DbType="VarChar(14)")]
		public string dpi
		{
			get
			{
				return this._dpi;
			}
			set
			{
				if ((this._dpi != value))
				{
					this.OndpiChanging(value);
					this.SendPropertyChanging();
					this._dpi = value;
					this.SendPropertyChanged("dpi");
					this.OndpiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaNacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> fechaNacimiento
		{
			get
			{
				return this._fechaNacimiento;
			}
			set
			{
				if ((this._fechaNacimiento != value))
				{
					this.OnfechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._fechaNacimiento = value;
					this.SendPropertyChanged("fechaNacimiento");
					this.OnfechaNacimientoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbPresentacion")]
	public partial class tbPresentacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codPresentacion;
		
		private string _presentacion;
		
		private EntitySet<tbProducto> _tbProducto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodPresentacionChanging(int value);
    partial void OncodPresentacionChanged();
    partial void OnpresentacionChanging(string value);
    partial void OnpresentacionChanged();
    #endregion
		
		public tbPresentacion()
		{
			this._tbProducto = new EntitySet<tbProducto>(new Action<tbProducto>(this.attach_tbProducto), new Action<tbProducto>(this.detach_tbProducto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPresentacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codPresentacion
		{
			get
			{
				return this._codPresentacion;
			}
			set
			{
				if ((this._codPresentacion != value))
				{
					this.OncodPresentacionChanging(value);
					this.SendPropertyChanging();
					this._codPresentacion = value;
					this.SendPropertyChanged("codPresentacion");
					this.OncodPresentacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_presentacion", DbType="VarChar(50)")]
		public string presentacion
		{
			get
			{
				return this._presentacion;
			}
			set
			{
				if ((this._presentacion != value))
				{
					this.OnpresentacionChanging(value);
					this.SendPropertyChanging();
					this._presentacion = value;
					this.SendPropertyChanged("presentacion");
					this.OnpresentacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbPresentacion_tbProducto", Storage="_tbProducto", ThisKey="codPresentacion", OtherKey="codPresentacion")]
		public EntitySet<tbProducto> tbProducto
		{
			get
			{
				return this._tbProducto;
			}
			set
			{
				this._tbProducto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbProducto(tbProducto entity)
		{
			this.SendPropertyChanging();
			entity.tbPresentacion = this;
		}
		
		private void detach_tbProducto(tbProducto entity)
		{
			this.SendPropertyChanging();
			entity.tbPresentacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbProducto")]
	public partial class tbProducto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codProducto;
		
		private System.Nullable<int> _codCategoria;
		
		private System.Nullable<int> _codPresentacion;
		
		private System.Nullable<int> _codTipoVenta;
		
		private string _producto;
		
		private string _descripcion;
		
		private EntityRef<tbCategoria> _tbCategoria;
		
		private EntityRef<tbPresentacion> _tbPresentacion;
		
		private EntityRef<tbTipoVenta> _tbTipoVenta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodProductoChanging(int value);
    partial void OncodProductoChanged();
    partial void OncodCategoriaChanging(System.Nullable<int> value);
    partial void OncodCategoriaChanged();
    partial void OncodPresentacionChanging(System.Nullable<int> value);
    partial void OncodPresentacionChanged();
    partial void OncodTipoVentaChanging(System.Nullable<int> value);
    partial void OncodTipoVentaChanged();
    partial void OnproductoChanging(string value);
    partial void OnproductoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public tbProducto()
		{
			this._tbCategoria = default(EntityRef<tbCategoria>);
			this._tbPresentacion = default(EntityRef<tbPresentacion>);
			this._tbTipoVenta = default(EntityRef<tbTipoVenta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codProducto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codProducto
		{
			get
			{
				return this._codProducto;
			}
			set
			{
				if ((this._codProducto != value))
				{
					if (this._tbCategoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodProductoChanging(value);
					this.SendPropertyChanging();
					this._codProducto = value;
					this.SendPropertyChanged("codProducto");
					this.OncodProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codCategoria", DbType="Int")]
		public System.Nullable<int> codCategoria
		{
			get
			{
				return this._codCategoria;
			}
			set
			{
				if ((this._codCategoria != value))
				{
					this.OncodCategoriaChanging(value);
					this.SendPropertyChanging();
					this._codCategoria = value;
					this.SendPropertyChanged("codCategoria");
					this.OncodCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codPresentacion", DbType="Int")]
		public System.Nullable<int> codPresentacion
		{
			get
			{
				return this._codPresentacion;
			}
			set
			{
				if ((this._codPresentacion != value))
				{
					if (this._tbPresentacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodPresentacionChanging(value);
					this.SendPropertyChanging();
					this._codPresentacion = value;
					this.SendPropertyChanged("codPresentacion");
					this.OncodPresentacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codTipoVenta", DbType="Int")]
		public System.Nullable<int> codTipoVenta
		{
			get
			{
				return this._codTipoVenta;
			}
			set
			{
				if ((this._codTipoVenta != value))
				{
					if (this._tbTipoVenta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncodTipoVentaChanging(value);
					this.SendPropertyChanging();
					this._codTipoVenta = value;
					this.SendPropertyChanged("codTipoVenta");
					this.OncodTipoVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_producto", DbType="VarChar(50)")]
		public string producto
		{
			get
			{
				return this._producto;
			}
			set
			{
				if ((this._producto != value))
				{
					this.OnproductoChanging(value);
					this.SendPropertyChanging();
					this._producto = value;
					this.SendPropertyChanged("producto");
					this.OnproductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(150)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbCategoria_tbProducto", Storage="_tbCategoria", ThisKey="codProducto", OtherKey="codCategoria", IsForeignKey=true)]
		public tbCategoria tbCategoria
		{
			get
			{
				return this._tbCategoria.Entity;
			}
			set
			{
				tbCategoria previousValue = this._tbCategoria.Entity;
				if (((previousValue != value) 
							|| (this._tbCategoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbCategoria.Entity = null;
						previousValue.tbProducto.Remove(this);
					}
					this._tbCategoria.Entity = value;
					if ((value != null))
					{
						value.tbProducto.Add(this);
						this._codProducto = value.codCategoria;
					}
					else
					{
						this._codProducto = default(int);
					}
					this.SendPropertyChanged("tbCategoria");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbPresentacion_tbProducto", Storage="_tbPresentacion", ThisKey="codPresentacion", OtherKey="codPresentacion", IsForeignKey=true)]
		public tbPresentacion tbPresentacion
		{
			get
			{
				return this._tbPresentacion.Entity;
			}
			set
			{
				tbPresentacion previousValue = this._tbPresentacion.Entity;
				if (((previousValue != value) 
							|| (this._tbPresentacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbPresentacion.Entity = null;
						previousValue.tbProducto.Remove(this);
					}
					this._tbPresentacion.Entity = value;
					if ((value != null))
					{
						value.tbProducto.Add(this);
						this._codPresentacion = value.codPresentacion;
					}
					else
					{
						this._codPresentacion = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbPresentacion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbTipoVenta_tbProducto", Storage="_tbTipoVenta", ThisKey="codTipoVenta", OtherKey="codTipoVenta", IsForeignKey=true)]
		public tbTipoVenta tbTipoVenta
		{
			get
			{
				return this._tbTipoVenta.Entity;
			}
			set
			{
				tbTipoVenta previousValue = this._tbTipoVenta.Entity;
				if (((previousValue != value) 
							|| (this._tbTipoVenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbTipoVenta.Entity = null;
						previousValue.tbProducto.Remove(this);
					}
					this._tbTipoVenta.Entity = value;
					if ((value != null))
					{
						value.tbProducto.Add(this);
						this._codTipoVenta = value.codTipoVenta;
					}
					else
					{
						this._codTipoVenta = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbTipoVenta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbSalida")]
	public partial class tbSalida : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codSalida;
		
		private System.Nullable<int> _codTipoSalida;
		
		private System.DateTime _fechaSalida;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodSalidaChanging(int value);
    partial void OncodSalidaChanged();
    partial void OncodTipoSalidaChanging(System.Nullable<int> value);
    partial void OncodTipoSalidaChanged();
    partial void OnfechaSalidaChanging(System.DateTime value);
    partial void OnfechaSalidaChanged();
    #endregion
		
		public tbSalida()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codSalida", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codSalida
		{
			get
			{
				return this._codSalida;
			}
			set
			{
				if ((this._codSalida != value))
				{
					this.OncodSalidaChanging(value);
					this.SendPropertyChanging();
					this._codSalida = value;
					this.SendPropertyChanged("codSalida");
					this.OncodSalidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codTipoSalida", DbType="Int")]
		public System.Nullable<int> codTipoSalida
		{
			get
			{
				return this._codTipoSalida;
			}
			set
			{
				if ((this._codTipoSalida != value))
				{
					this.OncodTipoSalidaChanging(value);
					this.SendPropertyChanging();
					this._codTipoSalida = value;
					this.SendPropertyChanged("codTipoSalida");
					this.OncodTipoSalidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaSalida", AutoSync=AutoSync.Always, DbType="DateTime2 NOT NULL", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.DateTime fechaSalida
		{
			get
			{
				return this._fechaSalida;
			}
			set
			{
				if ((this._fechaSalida != value))
				{
					this.OnfechaSalidaChanging(value);
					this.SendPropertyChanging();
					this._fechaSalida = value;
					this.SendPropertyChanged("fechaSalida");
					this.OnfechaSalidaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbTipoPersona")]
	public partial class tbTipoPersona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codTipoPersona;
		
		private string _tipoPersona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodTipoPersonaChanging(int value);
    partial void OncodTipoPersonaChanged();
    partial void OntipoPersonaChanging(string value);
    partial void OntipoPersonaChanged();
    #endregion
		
		public tbTipoPersona()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codTipoPersona", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codTipoPersona
		{
			get
			{
				return this._codTipoPersona;
			}
			set
			{
				if ((this._codTipoPersona != value))
				{
					this.OncodTipoPersonaChanging(value);
					this.SendPropertyChanging();
					this._codTipoPersona = value;
					this.SendPropertyChanged("codTipoPersona");
					this.OncodTipoPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoPersona", DbType="VarChar(50)")]
		public string tipoPersona
		{
			get
			{
				return this._tipoPersona;
			}
			set
			{
				if ((this._tipoPersona != value))
				{
					this.OntipoPersonaChanging(value);
					this.SendPropertyChanging();
					this._tipoPersona = value;
					this.SendPropertyChanged("tipoPersona");
					this.OntipoPersonaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbTipoSalida")]
	public partial class tbTipoSalida : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codTipoSalida;
		
		private string _tipoSalida;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodTipoSalidaChanging(int value);
    partial void OncodTipoSalidaChanged();
    partial void OntipoSalidaChanging(string value);
    partial void OntipoSalidaChanged();
    #endregion
		
		public tbTipoSalida()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codTipoSalida", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codTipoSalida
		{
			get
			{
				return this._codTipoSalida;
			}
			set
			{
				if ((this._codTipoSalida != value))
				{
					this.OncodTipoSalidaChanging(value);
					this.SendPropertyChanging();
					this._codTipoSalida = value;
					this.SendPropertyChanged("codTipoSalida");
					this.OncodTipoSalidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoSalida", DbType="VarChar(50)")]
		public string tipoSalida
		{
			get
			{
				return this._tipoSalida;
			}
			set
			{
				if ((this._tipoSalida != value))
				{
					this.OntipoSalidaChanging(value);
					this.SendPropertyChanging();
					this._tipoSalida = value;
					this.SendPropertyChanged("tipoSalida");
					this.OntipoSalidaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbTipoVenta")]
	public partial class tbTipoVenta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codTipoVenta;
		
		private string _tipoVenta;
		
		private EntitySet<tbProducto> _tbProducto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodTipoVentaChanging(int value);
    partial void OncodTipoVentaChanged();
    partial void OntipoVentaChanging(string value);
    partial void OntipoVentaChanged();
    #endregion
		
		public tbTipoVenta()
		{
			this._tbProducto = new EntitySet<tbProducto>(new Action<tbProducto>(this.attach_tbProducto), new Action<tbProducto>(this.detach_tbProducto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codTipoVenta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codTipoVenta
		{
			get
			{
				return this._codTipoVenta;
			}
			set
			{
				if ((this._codTipoVenta != value))
				{
					this.OncodTipoVentaChanging(value);
					this.SendPropertyChanging();
					this._codTipoVenta = value;
					this.SendPropertyChanged("codTipoVenta");
					this.OncodTipoVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoVenta", DbType="VarChar(50)")]
		public string tipoVenta
		{
			get
			{
				return this._tipoVenta;
			}
			set
			{
				if ((this._tipoVenta != value))
				{
					this.OntipoVentaChanging(value);
					this.SendPropertyChanging();
					this._tipoVenta = value;
					this.SendPropertyChanged("tipoVenta");
					this.OntipoVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbTipoVenta_tbProducto", Storage="_tbProducto", ThisKey="codTipoVenta", OtherKey="codTipoVenta")]
		public EntitySet<tbProducto> tbProducto
		{
			get
			{
				return this._tbProducto;
			}
			set
			{
				this._tbProducto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbProducto(tbProducto entity)
		{
			this.SendPropertyChanging();
			entity.tbTipoVenta = this;
		}
		
		private void detach_tbProducto(tbProducto entity)
		{
			this.SendPropertyChanging();
			entity.tbTipoVenta = null;
		}
	}
}
#pragma warning restore 1591
